"""Population and source reconciliation for the 2010-11 MVP Rose carousel."""
from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from scripts.prototypes import bulls_season_zone_charts as charts


ROOT = Path(__file__).resolve().parents[1]
DATA = (
    ROOT / "docs" / "visuals" /
    "2026-08-26-2010-11-mvp-rose-zone-charts" / "data"
)
MIN_TOTAL_FGA = 300


def test_visible_total_fga_floor_selects_the_rotation_population():
    leaderboard = pd.read_csv(DATA / "bulls-season-fga-leaderboard-2010-11.csv")
    selected = charts.select_players(
        leaderboard, minimum=MIN_TOTAL_FGA, limit=0
    )

    assert selected.PLAYER_NAME.tolist() == [
        "Derrick Rose",
        "Luol Deng",
        "Carlos Boozer",
        "Kyle Korver",
        "Taj Gibson",
        "Ronnie Brewer",
        "Joakim Noah",
        "C.J. Watson",
        "Keith Bogans",
    ]
    assert selected.FGA.min() == 307
    assert leaderboard.loc[leaderboard.FGA < MIN_TOTAL_FGA, "FGA"].max() == 186
    assert selected.FGA.sum() / leaderboard.FGA.sum() == pytest.approx(
        6186 / 6587
    )


def test_threshold_audit_proves_lowest_volume_pages_remain_descriptive():
    audit = pd.read_csv(DATA / "threshold-audit.csv")

    selected = audit[audit.qualifies_300_fga]
    excluded = audit[~audit.qualifies_300_fga]

    assert len(selected) == 9
    assert selected.fga.ge(MIN_TOTAL_FGA).all()
    assert selected.rated_zones.ge(3).all()
    assert selected.rated_fga_share_pct.between(89, 100).all()
    assert excluded.player.tolist() == ["Kurt Thomas", "Omer Asik"]


def test_every_qualified_shot_log_reconciles_to_official_fga_and_fgm():
    leaderboard = pd.read_csv(DATA / "bulls-season-fga-leaderboard-2010-11.csv")
    selected = charts.select_players(
        leaderboard, minimum=MIN_TOTAL_FGA, limit=0
    )

    for player in selected.itertuples(index=False):
        path = DATA / (
            f"2010-11-{charts.player_slug(player.PLAYER_NAME)}-bulls-shots.csv"
        )
        shots = pd.read_csv(path)
        assert len(shots) == int(player.FGA)
        assert int(shots.shot_made.sum()) == int(player.FGM)


def test_historical_league_location_gap_is_explicit_and_bounded():
    path = DATA / "league-unclassifiable-shots-2010-11.csv"
    if not path.exists():
        pytest.skip("generated by the full baseline build")
    excluded = pd.read_csv(path)

    assert len(excluded) == 29
    assert excluded[["loc_x", "loc_y", "shot_zone"]].isna().all().all()


def test_team_chart_uses_every_bulls_attempt_and_reconciles_official_totals():
    shots_path = DATA / "bulls-team-shots-2010-11.csv"
    totals_path = DATA / "bulls-team-totals-2010-11.csv"
    if not shots_path.exists() or not totals_path.exists():
        pytest.skip("generated by the all-team build")
    shots = pd.read_csv(shots_path)
    totals = pd.read_csv(totals_path).iloc[0]

    assert len(shots) == int(totals.FGA) == 6587
    assert int(shots.shot_made.sum()) == int(totals.FGM) == 3042


def test_team_zone_audit_colours_every_observed_zone():
    path = DATA / "bulls-team-zone-splits-2010-11.csv"
    if not path.exists():
        pytest.skip("generated by the all-team build")
    zones = pd.read_csv(path)

    assert len(zones) == 12
    assert zones.fga.sum() == 6570
    assert 6587 - zones.fga.sum() == 17  # backcourt attempts stay in total FGA
    assert zones.fga.min() == 188
    assert zones.rated.all()
    assert zones.fga_share_pct.sum() == pytest.approx(
        zones.fga.sum() / 6587 * 100, abs=0.001
    )
